# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170517_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
