# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 06:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20170517_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='store_email',
            field=models.CharField(max_length=100),
        ),
    ]
