# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170517_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='store_id',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
