# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_auto_20170527_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=50)),
                ('store_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Store')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cmanage',
            unique_together=set([('user_email', 'store_email')]),
        ),
    ]
